# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x0bmirrorbrain\"\x9a\x01\n\rActionRequest\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x36\n\x06params\x18\x02 \x03(\x0b\x32&.mirrorbrain.ActionRequest.ParamsEntry\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"[\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"\'\n\x12\x45ventStreamRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"D\n\x0bSystemEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\" \n\x0bPingRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"0\n\x0cPingResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05ready\x18\x02 \x01(\x08\x32\xe1\x01\n\x0b\x41gentBridge\x12\x44\n\x07\x45xecute\x12\x1a.mirrorbrain.ActionRequest\x1a\x1b.mirrorbrain.ActionResponse\"\x00\x12M\n\x0cStreamEvents\x12\x1f.mirrorbrain.EventStreamRequest\x1a\x18.mirrorbrain.SystemEvent\"\x00\x30\x01\x12=\n\x04Ping\x12\x18.mirrorbrain.PingRequest\x1a\x19.mirrorbrain.PingResponse\"\x00\x42\x1e\n\x1a\x63om.mirrorbrainmobile.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.mirrorbrainmobile.grpcP\001'
  _globals['_ACTIONREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_ACTIONREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONREQUEST']._serialized_start=29
  _globals['_ACTIONREQUEST']._serialized_end=183
  _globals['_ACTIONREQUEST_PARAMSENTRY']._serialized_start=138
  _globals['_ACTIONREQUEST_PARAMSENTRY']._serialized_end=183
  _globals['_ACTIONRESPONSE']._serialized_start=185
  _globals['_ACTIONRESPONSE']._serialized_end=276
  _globals['_EVENTSTREAMREQUEST']._serialized_start=278
  _globals['_EVENTSTREAMREQUEST']._serialized_end=317
  _globals['_SYSTEMEVENT']._serialized_start=319
  _globals['_SYSTEMEVENT']._serialized_end=387
  _globals['_PINGREQUEST']._serialized_start=389
  _globals['_PINGREQUEST']._serialized_end=421
  _globals['_PINGRESPONSE']._serialized_start=423
  _globals['_PINGRESPONSE']._serialized_end=471
  _globals['_AGENTBRIDGE']._serialized_start=474
  _globals['_AGENTBRIDGE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
