# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentBridgeStub(object):
    """The Bridge Service: Connects the 'Mind' (Python/Termux) to the 'Body' (Android System)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/mirrorbrain.AgentBridge/Execute',
                request_serializer=agent__pb2.ActionRequest.SerializeToString,
                response_deserializer=agent__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/mirrorbrain.AgentBridge/StreamEvents',
                request_serializer=agent__pb2.EventStreamRequest.SerializeToString,
                response_deserializer=agent__pb2.SystemEvent.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/mirrorbrain.AgentBridge/Ping',
                request_serializer=agent__pb2.PingRequest.SerializeToString,
                response_deserializer=agent__pb2.PingResponse.FromString,
                _registered_method=True)


class AgentBridgeServicer(object):
    """The Bridge Service: Connects the 'Mind' (Python/Termux) to the 'Body' (Android System)
    """

    def Execute(self, request, context):
        """Execute a specific action (e.g., "call mom", "launch app")
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Stream system events to the brain (e.g., "notification received", "screen on")
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Heartbeat to ensure connection is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=agent__pb2.ActionRequest.FromString,
                    response_serializer=agent__pb2.ActionResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=agent__pb2.EventStreamRequest.FromString,
                    response_serializer=agent__pb2.SystemEvent.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent__pb2.PingRequest.FromString,
                    response_serializer=agent__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mirrorbrain.AgentBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mirrorbrain.AgentBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentBridge(object):
    """The Bridge Service: Connects the 'Mind' (Python/Termux) to the 'Body' (Android System)
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorbrain.AgentBridge/Execute',
            agent__pb2.ActionRequest.SerializeToString,
            agent__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mirrorbrain.AgentBridge/StreamEvents',
            agent__pb2.EventStreamRequest.SerializeToString,
            agent__pb2.SystemEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorbrain.AgentBridge/Ping',
            agent__pb2.PingRequest.SerializeToString,
            agent__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
